### ISSUE TITLE
Speckle-Unreal Tutorials

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-unreal#33]
Right now, our our tutorials are lacking, I plan on creating a few tutorials on the following topics

- [ ] Materials override workflow
- [x] Customising conversion - https://speckle.systems/tutorials/unreal-developing-custom-conversion-logic/
- [x] BP nodes

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
