### ISSUE TITLE
Detach panel functionality from SpeckleUnrealManager

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-unreal#4]
TBD, from a quick discussion with @cristi8: 

- make the panel independent, and allow it to: 
- [ ] read accounts from the local sqlite db
- [ ] get streams from those accounts
- [ ] get branches (but we could only see the master, which is actually `main`, etc.)
- [x] get commits (already done!)
- [x] and, of course, import in referenced objects. 

without relying on the SpeckleUnrealManager.

**Comment by JR-Morgan** [comment]
Closed as structure of project has changed.
