### ISSUE TITLE
Vertex colors are not converted

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-unreal#46]
We never implemented support for converting meshes with Vertex Colours.
Mesh to native conversion ignores vertex colors which maybe useful to convert.

https://github.com/specklesystems/speckle-unreal/blob/dcc14bf8261edbce53c2f67df6476156febe63ed/Source/SpeckleUnreal/Private/Conversion/Converters/StaticMeshConverter.cpp#L280-L289

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
